# Generated by Django 5.2 on 2025-08-10 15:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0003_alter_run_athlete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(900)])),
                ('goals', models.CharField(blank=True, max_length=140, null=True)),
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
