# Generated by Django 5.2 on 2025-08-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0007_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='positions',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
