# Generated by Django 5.2 on 2025-08-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0008_alter_positions_latitude_alter_positions_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
