# Generated by Django 5.2 on 2025-08-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0009_run_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='full_name',
            field=models.CharField(choices=[('run10', 'Сделай 10 Забегов!'), ('run50km', 'Пробеги 50 километров!')], default='run10', max_length=55),
        ),
    ]
