# Generated by Django 5.2 on 2025-08-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0010_alter_challenge_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectibleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('uid', models.CharField(max_length=140)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('picture', models.URLField()),
                ('value', models.IntegerField()),
            ],
        ),
    ]
