# Generated by Django 5.2 on 2025-08-19 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_run', '0011_collectibleitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteinfo',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='athlete_info', to='app_run.collectibleitem'),
        ),
        migrations.AddField(
            model_name='collectibleitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='collectible_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
