# Generated by Django 5.2 on 2025-09-24 14:00

from django.db import migrations, models

import app_run.validators


class Migration(migrations.Migration):
    dependencies = [
        ('app_run', '0012_athleteinfo_items_collectibleitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectibleitem',
            name='latitude',
            field=models.FloatField(validators=[app_run.validators.latitude_validator]),
        ),
        migrations.AlterField(
            model_name='collectibleitem',
            name='longitude',
            field=models.FloatField(validators=[app_run.validators.longitude_validator]),
        ),
    ]
