# Generated by Django 5.2 on 2025-09-25 15:49

from django.db import migrations, models

import app_run.validators


class Migration(migrations.Migration):
    dependencies = [
        ('app_run', '0013_alter_collectibleitem_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='run_time_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='positions',
            name='latitude',
            field=models.FloatField(validators=[app_run.validators.latitude_validator]),
        ),
        migrations.AlterField(
            model_name='positions',
            name='longitude',
            field=models.FloatField(validators=[app_run.validators.longitude_validator]),
        ),
    ]
