# Generated by Django 5.2 on 2025-09-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_run', '0014_positions_date_time_run_run_time_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='positions',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
