# Generated by Django 5.2 on 2025-10-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_run', '0015_positions_distance_positions_speed_run_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='full_name',
            field=models.CharField(choices=[('run10', 'Сделай 10 Забегов!'), ('run50km', 'Пробеги 50 километров!'),
                                            ('run2kmin10m', '2 километра за 10 минут!')], default='run10',
                                   max_length=55),
        ),
    ]
