# Generated by Django 5.2 on 2025-10-07 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_run', '0017_subscribe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athleteinfo',
            name='items',
        ),
        migrations.RemoveField(
            model_name='collectibleitem',
            name='user',
        ),
        migrations.AddField(
            model_name='collectibleitem',
            name='user',
            field=models.ManyToManyField(related_name='collectible_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
