# Generated by Django 5.2 on 2025-10-07 17:28

from django.db import migrations, models

import app_run.validators


class Migration(migrations.Migration):
    dependencies = [
        ('app_run', '0018_remove_athleteinfo_items_remove_collectibleitem_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True,
                                                   validators=[app_run.validators.rating_validator]),
        ),
    ]
